### ISSUE TITLE
[Bug]: deployment-server-ui Devices shows a white screen

### ISSUE THREAD

**Issue by KevinK-9** [eclipsesource/cdtcloud-deploymentserver#105]
### Current Behaviour

When opening the Devices page in the deployment server frontend, nothing is displayed and the screen stays white.

### Expected Behaviour

The page should show a table with the devices.

### Steps to reproduce the problem

1. run the application
2. go to the site where deployment-server-ui is running
3. click on Devices in the sidebar

### Code rev. hash/commit

653a1aa23320960905aa2216d59c6d8440314284

### Node version

16.13

### Operating system

Windows 10 x64

**Comment by Gozzim** [comment]
Can you provide an error message and possibly the file and loc of the issue?
